name = "OSReconstruction"
version = "0.1.0"
defaultTargets = ["OSReconstruction"]

[[require]]
name = "GaussianField"
git = "https://github.com/mrdouglasny/gaussian-field.git"
rev = "36ae6dd"
subDir = "."

[[require]]
name = "HilleYosida"
git = "https://github.com/mrdouglasny/hille-yosida.git"
rev = "7651cad"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[lean_lib]]
name = "OSReconstruction"
