import Mathlib.Analysis.Complex.Basic
import Mathlib.Topology.ContinuousMap.StoneWeierstrass
import Mathlib.Topology.UrysohnsLemma

/-!
# Product Stone-Weierstrass

On a product of compact Hausdorff spaces, the subalgebra generated by pullbacks
from the two factors is dense in the algebra of continuous real-valued
functions.
-/

noncomputable section

open ContinuousMap

namespace OSReconstruction

variable {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]

/-- Projection from `X × Y` to the first factor as a continuous map. -/
def fstProj : C(X × Y, X) := ⟨Prod.fst, continuous_fst⟩

/-- Projection from `X × Y` to the second factor as a continuous map. -/
def sndProj : C(X × Y, Y) := ⟨Prod.snd, continuous_snd⟩

/-- The subalgebra of continuous functions on `X × Y` generated by pullbacks
from the two factors. -/
def productAlgebra : Subalgebra ℝ C(X × Y, ℝ) :=
  Algebra.adjoin ℝ
    (Set.range (fun f : C(X, ℝ) => f.comp (fstProj (X := X) (Y := Y))) ∪
      Set.range (fun g : C(Y, ℝ) => g.comp (sndProj (X := X) (Y := Y))))

/-- A pullback from the first factor lies in the generated product algebra. -/
theorem pullbackFst_mem (f : C(X, ℝ)) :
    f.comp ⟨Prod.fst, continuous_fst⟩ ∈ productAlgebra (X := X) (Y := Y) :=
  Algebra.subset_adjoin (Set.mem_union_left _ ⟨f, rfl⟩)

/-- A pullback from the second factor lies in the generated product algebra. -/
theorem pullbackSnd_mem (g : C(Y, ℝ)) :
    g.comp ⟨Prod.snd, continuous_snd⟩ ∈ productAlgebra (X := X) (Y := Y) :=
  Algebra.subset_adjoin (Set.mem_union_right _ ⟨g, rfl⟩)

/-- The product algebra separates points on `X × Y`. -/
theorem productAlgebra_separatesPoints [CompactSpace X] [CompactSpace Y] [T2Space X] [T2Space Y] :
    (productAlgebra (X := X) (Y := Y)).SeparatesPoints := by
  intro ⟨x₁, y₁⟩ ⟨x₂, y₂⟩ hne
  by_cases hx : x₁ = x₂
  · have hy : y₁ ≠ y₂ := fun h => hne (Prod.ext hx h)
    obtain ⟨g, hg0, hg1, -⟩ := exists_continuous_zero_one_of_isClosed
      (isClosed_singleton : IsClosed ({y₁} : Set Y))
      (isClosed_singleton : IsClosed ({y₂} : Set Y))
      (Set.disjoint_singleton.mpr hy)
    refine ⟨g.comp ⟨Prod.snd, continuous_snd⟩, ?_, ?_⟩
    · exact ⟨_, pullbackSnd_mem g, rfl⟩
    simp only [ContinuousMap.comp_apply, ContinuousMap.coe_mk]
    rw [hg0 (Set.mem_singleton y₁), hg1 (Set.mem_singleton y₂)]
    exact one_ne_zero.symm
  · obtain ⟨f, hf0, hf1, -⟩ := exists_continuous_zero_one_of_isClosed
      (isClosed_singleton : IsClosed ({x₁} : Set X))
      (isClosed_singleton : IsClosed ({x₂} : Set X))
      (Set.disjoint_singleton.mpr hx)
    refine ⟨f.comp ⟨Prod.fst, continuous_fst⟩, ?_, ?_⟩
    · exact ⟨_, pullbackFst_mem f, rfl⟩
    simp only [ContinuousMap.comp_apply, ContinuousMap.coe_mk]
    rw [hf0 (Set.mem_singleton x₁), hf1 (Set.mem_singleton x₂)]
    exact one_ne_zero.symm

/-- Stone-Weierstrass on a compact product: pullbacks from the two factors
generate a dense subalgebra of `C(X × Y, ℝ)`. -/
theorem productAlgebra_dense [CompactSpace X] [CompactSpace Y] [T2Space X] [T2Space Y] :
    (productAlgebra (X := X) (Y := Y)).topologicalClosure = ⊤ := by
  exact subalgebra_topologicalClosure_eq_top_of_separatesPoints
    productAlgebra productAlgebra_separatesPoints

/-- The star-subalgebra of continuous complex-valued functions on `X × Y`
generated by pullbacks from the two factors. -/
def complexProductStarAlgebra : StarSubalgebra ℂ C(X × Y, ℂ) :=
  StarAlgebra.adjoin ℂ
    (Set.range (fun f : C(X, ℂ) => f.comp (fstProj (X := X) (Y := Y))) ∪
      Set.range (fun g : C(Y, ℂ) => g.comp (sndProj (X := X) (Y := Y))))

/-- A complex-valued pullback from the first factor lies in the generated
product star-subalgebra. -/
theorem complexPullbackFst_mem (f : C(X, ℂ)) :
    f.comp ⟨Prod.fst, continuous_fst⟩ ∈ complexProductStarAlgebra (X := X) (Y := Y) := by
  exact StarAlgebra.mem_adjoin_of_mem (R := ℂ)
    (Set.mem_union_left _ ⟨f, rfl⟩)

/-- A complex-valued pullback from the second factor lies in the generated
product star-subalgebra. -/
theorem complexPullbackSnd_mem (g : C(Y, ℂ)) :
    g.comp ⟨Prod.snd, continuous_snd⟩ ∈ complexProductStarAlgebra (X := X) (Y := Y) := by
  exact StarAlgebra.mem_adjoin_of_mem (R := ℂ)
    (Set.mem_union_right _ ⟨g, rfl⟩)

/-- The complex product star-subalgebra separates points on `X × Y`. -/
theorem complexProductStarAlgebra_separatesPoints
    [CompactSpace X] [CompactSpace Y] [T2Space X] [T2Space Y] :
    (complexProductStarAlgebra (X := X) (Y := Y)).SeparatesPoints := by
  intro ⟨x₁, y₁⟩ ⟨x₂, y₂⟩ hne
  by_cases hx : x₁ = x₂
  · have hy : y₁ ≠ y₂ := fun h => hne (Prod.ext hx h)
    obtain ⟨g, hg0, hg1, -⟩ := exists_continuous_zero_one_of_isClosed
      (isClosed_singleton : IsClosed ({y₁} : Set Y))
      (isClosed_singleton : IsClosed ({y₂} : Set Y))
      (Set.disjoint_singleton.mpr hy)
    let gC : C(Y, ℂ) := ⟨fun y => (g y : ℂ), Complex.continuous_ofReal.comp g.continuous⟩
    refine ⟨gC.comp ⟨Prod.snd, continuous_snd⟩, ?_, ?_⟩
    · exact ⟨_, complexPullbackSnd_mem gC, rfl⟩
    simp only [gC, ContinuousMap.comp_apply, ContinuousMap.coe_mk]
    rw [hg0 (Set.mem_singleton y₁), hg1 (Set.mem_singleton y₂)]
    norm_num
  · obtain ⟨f, hf0, hf1, -⟩ := exists_continuous_zero_one_of_isClosed
      (isClosed_singleton : IsClosed ({x₁} : Set X))
      (isClosed_singleton : IsClosed ({x₂} : Set X))
      (Set.disjoint_singleton.mpr hx)
    let fC : C(X, ℂ) := ⟨fun x => (f x : ℂ), Complex.continuous_ofReal.comp f.continuous⟩
    refine ⟨fC.comp ⟨Prod.fst, continuous_fst⟩, ?_, ?_⟩
    · exact ⟨_, complexPullbackFst_mem fC, rfl⟩
    simp only [fC, ContinuousMap.comp_apply, ContinuousMap.coe_mk]
    rw [hf0 (Set.mem_singleton x₁), hf1 (Set.mem_singleton x₂)]
    norm_num

/-- Complex Stone-Weierstrass on a compact product: pullbacks from the two
factors generate a dense star-subalgebra of `C(X × Y, ℂ)`. -/
theorem complexProductStarAlgebra_dense
    [CompactSpace X] [CompactSpace Y] [T2Space X] [T2Space Y] :
    (complexProductStarAlgebra (X := X) (Y := Y)).topologicalClosure = ⊤ := by
  exact ContinuousMap.starSubalgebra_topologicalClosure_eq_top_of_separatesPoints
    _ complexProductStarAlgebra_separatesPoints

end OSReconstruction
