import Mathlib.GroupTheory.Perm.Fin

namespace BHW

/-- Any permutation of `Fin n` can be written as a product of adjacent transpositions
    `swap(i, i+1)`. This is an induction principle: to prove a property for all
    permutations, it suffices to prove it for the identity and show closure under
    left-multiplication by adjacent transpositions.

    Uses `Equiv.Perm.mclosure_swap_castSucc_succ` (the submonoid generated by
    adjacent transpositions is `⊤`) together with `Submonoid.closure_induction`. -/
theorem Fin.Perm.adjSwap_induction {n : ℕ}
    {motive : Equiv.Perm (Fin n) → Prop}
    (one : motive 1)
    (adj_mul : ∀ (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n),
      motive σ → motive (Equiv.swap i ⟨i.val + 1, hi⟩ * σ))
    (τ : Equiv.Perm (Fin n)) : motive τ := by
  -- For n = 0: Perm (Fin 0) is trivial, τ = 1
  rcases n with _ | n
  · have : τ = 1 := Subsingleton.elim _ _
    rw [this]
    exact one
  -- For n + 1: use mclosure_swap_castSucc_succ
  -- Define motive' on the submonoid: "left-multiplying by x preserves motive"
  suffices h : ∀ (x : Equiv.Perm (Fin (n + 1))),
      x ∈ Submonoid.closure (Set.range fun i : Fin n => Equiv.swap i.castSucc i.succ) →
      ∀ σ, motive σ → motive (x * σ) by
    have h_top := Equiv.Perm.mclosure_swap_castSucc_succ n
    have hτ_mem : τ ∈ (⊤ : Submonoid (Equiv.Perm (Fin (n + 1)))) := Submonoid.mem_top τ
    rw [← h_top] at hτ_mem
    have := h τ hτ_mem 1 one
    rwa [mul_one] at this
  intro x hx
  exact Submonoid.closure_induction
    (motive := fun x _ => ∀ σ, motive σ → motive (x * σ))
    (mem := fun g hg σ hσ => by
      obtain ⟨i, rfl⟩ := hg
      -- g = swap(i.castSucc, i.succ), which is an adjacent transposition
      have hi : (i.castSucc).val + 1 < n + 1 := by simp [Fin.castSucc]
      show motive (Equiv.swap i.castSucc i.succ * σ)
      have h_eq : i.succ = ⟨(i.castSucc).val + 1, hi⟩ := by
        ext
        simp [Fin.castSucc, Fin.succ]
      rw [h_eq]
      exact adj_mul σ i.castSucc hi hσ)
    (one := fun σ hσ => by rwa [one_mul])
    (mul := fun a b _ _ ha hb σ hσ => by
      rw [mul_assoc]
      exact ha _ (hb σ hσ))
    hx

/-- Right-multiplication variant of `Fin.Perm.adjSwap_induction`.
    To prove a property for all permutations, it suffices to prove it for `1`
    and show closure under right multiplication by adjacent transpositions. -/
theorem Fin.Perm.adjSwap_induction_right {n : ℕ}
    {motive : Equiv.Perm (Fin n) → Prop}
    (one : motive 1)
    (mul_adj : ∀ (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n),
      motive σ → motive (σ * Equiv.swap i ⟨i.val + 1, hi⟩))
    (τ : Equiv.Perm (Fin n)) : motive τ := by
  have h_inv : ∀ σ : Equiv.Perm (Fin n), motive (σ⁻¹) := by
    intro σ
    refine Fin.Perm.adjSwap_induction
      (motive := fun ρ : Equiv.Perm (Fin n) => motive (ρ⁻¹))
      ?_ ?_ σ
    · simpa using one
    · intro ρ i hi hρ
      simpa [mul_assoc] using mul_adj (ρ⁻¹) i hi hρ
  simpa using h_inv τ⁻¹

end BHW
