/-
Copyright (c) 2026 ModularPhysics Contributors.
Released under Apache 2.0 license.
Authors: ModularPhysics Contributors
-/
import OSReconstruction.SCV.DistributionalEOWKernelFactorization

/-!
# Product-Kernel Covariance on Sheared Product Tests

This file proves the sign-sensitive product-test consequence of global product
kernel covariance.  It is intentionally only a generator-level theorem: the
promotion from product tests to all mixed Schwartz tests is the separate
Schwartz kernel/density theorem `schwartzKernel₂_extension`.
-/

noncomputable section

open Complex MeasureTheory

namespace SCV

@[simp]
theorem translateSchwartz_zero {m : ℕ}
    (ψ : SchwartzMap (Fin m → ℝ) ℂ) :
    translateSchwartz (0 : Fin m → ℝ) ψ = ψ := by
  ext t
  simp [translateSchwartz_apply]

/-- Global product-kernel covariance implies real-fiber invariance of the
sheared functional on every sheared product test.

This is the checked generator-level sign calculation.  The full theorem
`IsComplexRealFiberTranslationInvariant (shearedProductKernelFunctional K)`
requires the mixed product-tensor density/kernel-extension theorem to promote
this identity from sheared product tests to all mixed Schwartz tests. -/
theorem shearedProductKernel_fiberTranslate_shearedTensor_eq_self_of_productCovariant
    {m : ℕ}
    (K : SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ →L[ℂ] ℂ)
    (hcov : ProductKernelRealTranslationCovariantGlobal K)
    (a : Fin m → ℝ)
    (φ : SchwartzMap (ComplexChartSpace m) ℂ)
    (ψ : SchwartzMap (Fin m → ℝ) ℂ) :
    shearedProductKernelFunctional K
      (complexRealFiberTranslateSchwartzCLM a
        ((SchwartzMap.compCLMOfContinuousLinearEquiv ℂ (realConvolutionShearCLE m))
          (schwartzTensorProduct₂ φ ψ))) =
    shearedProductKernelFunctional K
      ((SchwartzMap.compCLMOfContinuousLinearEquiv ℂ (realConvolutionShearCLE m))
        (schwartzTensorProduct₂ φ ψ)) := by
  rw [complexRealFiberTranslate_shearedTensor_eq]
  simp [shearedProductKernelFunctional, ContinuousLinearMap.comp_apply]
  have h := hcov (-a) φ (translateSchwartz a ψ)
  simpa [translateSchwartz_translateSchwartz] using h

/-- The sheared product tests generated by two-space tensor products. -/
def shearedProductTensorSet (m : ℕ) :
    Set (SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ) :=
  {F | ∃ (φ : SchwartzMap (ComplexChartSpace m) ℂ)
      (ψ : SchwartzMap (Fin m → ℝ) ℂ),
    F = (SchwartzMap.compCLMOfContinuousLinearEquiv ℂ (realConvolutionShearCLE m))
      (schwartzTensorProduct₂ φ ψ)}

/-- The complex linear span of sheared product tests. -/
def shearedProductTensorSpan (m : ℕ) :
    Submodule ℂ (SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ) :=
  Submodule.span ℂ (shearedProductTensorSet m)

/-- The exact dense-span hypothesis needed to promote product-test covariance
to full mixed-Schwartz fiber-translation invariance.

This is the remaining product-density/kernel-extension blocker.  It is kept as
an explicit hypothesis in the conditional descent theorem below. -/
def ShearedProductTensorDense (m : ℕ) : Prop :=
  Dense ((shearedProductTensorSpan m : Set
    (SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ)))

/-- The unsheared product tests generated by two-space tensor products. -/
def productTensorSet (m : ℕ) :
    Set (SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ) :=
  {F | ∃ (φ : SchwartzMap (ComplexChartSpace m) ℂ)
      (ψ : SchwartzMap (Fin m → ℝ) ℂ),
    F = schwartzTensorProduct₂ φ ψ}

/-- The complex linear span of unsheared product tests. -/
def productTensorSpan (m : ℕ) :
    Submodule ℂ (SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ) :=
  Submodule.span ℂ (productTensorSet m)

/-- The standard mixed two-space product-density blocker. -/
def ProductTensorDense (m : ℕ) : Prop :=
  Dense ((productTensorSpan m : Set
    (SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ)))

/-- Sheared product tests are exactly the image of unsheared product tests under
the real-convolution shear. -/
theorem shearedProductTensorSet_eq_image_productTensorSet {m : ℕ} :
    shearedProductTensorSet m =
      (SchwartzMap.compCLMOfContinuousLinearEquiv ℂ (realConvolutionShearCLE m)) ''
        productTensorSet m := by
  ext F
  constructor
  · rintro ⟨φ, ψ, rfl⟩
    exact ⟨schwartzTensorProduct₂ φ ψ, ⟨φ, ψ, rfl⟩, rfl⟩
  · rintro ⟨G, ⟨φ, ψ, rfl⟩, rfl⟩
    exact ⟨φ, ψ, rfl⟩

/-- The sheared product span is the image of the unsheared product span under
the real-convolution shear. -/
theorem shearedProductTensorSpan_eq_productTensorSpan_map {m : ℕ} :
    shearedProductTensorSpan m =
      (productTensorSpan m).map
        ((SchwartzMap.compCLMOfContinuousLinearEquiv ℂ (realConvolutionShearCLE m) :
          SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ →L[ℂ]
            SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ).toLinearMap) := by
  rw [shearedProductTensorSpan, productTensorSpan,
    shearedProductTensorSet_eq_image_productTensorSet, Submodule.map_span]
  rfl

/-- Density of unsheared product tests transports to density of sheared product
tests through the real-convolution shear equivalence. -/
theorem shearedProductTensorDense_of_productTensorDense {m : ℕ}
    (hdense : ProductTensorDense m) : ShearedProductTensorDense m := by
  change Dense ((productTensorSpan m : Set
    (SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ))) at hdense
  change Dense ((shearedProductTensorSpan m : Set
    (SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ)))
  rw [Submodule.dense_iff_topologicalClosure_eq_top] at hdense ⊢
  let shear : SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ →L[ℂ]
      SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ :=
    SchwartzMap.compCLMOfContinuousLinearEquiv ℂ (realConvolutionShearCLE m)
  have hsurj : Function.Surjective shear := by
    intro F
    refine ⟨(SchwartzMap.compCLMOfContinuousLinearEquiv ℂ
      (realConvolutionShearCLE m).symm) F, ?_⟩
    change shear ((SchwartzMap.compCLMOfContinuousLinearEquiv ℂ
      (realConvolutionShearCLE m).symm) F) = F
    exact compCLMOfContinuousLinearEquiv_symm_left_inv
      (e := realConvolutionShearCLE m) F
  have hmap_dense :
      (((productTensorSpan m).map shear.toLinearMap).topologicalClosure) = ⊤ := by
    exact hsurj.denseRange.topologicalClosure_map_submodule (f := shear) hdense
  rw [shearedProductTensorSpan_eq_productTensorSpan_map]
  exact hmap_dense

/-- Continuous linear maps agreeing on a dense set agree everywhere. -/
private theorem continuousLinearMap_eq_of_eq_on_dense
    {𝕜 : Type*} [Semiring 𝕜]
    {E : Type*} [TopologicalSpace E] [AddCommMonoid E] [Module 𝕜 E]
    {F : Type*} [TopologicalSpace F] [AddCommGroup F] [Module 𝕜 F] [T2Space F]
    (T₁ T₂ : E →L[𝕜] F) {S : Set E} (hS : Dense S)
    (hT : ∀ x ∈ S, T₁ x = T₂ x) :
    T₁ = T₂ := by
  ext x
  have hclosed : IsClosed {x : E | T₁ x = T₂ x} :=
    isClosed_eq T₁.continuous T₂.continuous
  exact hclosed.closure_subset_iff.mpr (fun y hy => hT y hy) (hS.closure_eq ▸ trivial)

/-- Product covariance plus density of sheared product tests promotes the
generator-level covariance identity to full real-fiber translation invariance
of the sheared product-kernel functional. -/
theorem shearedProductKernel_fiberInvariant_of_productCovariant_of_shearedProductTensorDense
    {m : ℕ}
    (hdense : ShearedProductTensorDense m)
    (K : SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ →L[ℂ] ℂ)
    (hcov : ProductKernelRealTranslationCovariantGlobal K) :
    IsComplexRealFiberTranslationInvariant (shearedProductKernelFunctional K) := by
  intro a
  let L₁ : SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ →L[ℂ] ℂ :=
    (shearedProductKernelFunctional K).comp (complexRealFiberTranslateSchwartzCLM a)
  let L₂ : SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ →L[ℂ] ℂ :=
    shearedProductKernelFunctional K
  have hspan : ∀ F ∈ shearedProductTensorSpan m, L₁ F = L₂ F := by
    intro F hF
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hF
    · intro G hG
      rcases hG with ⟨φ, ψ, rfl⟩
      exact shearedProductKernel_fiberTranslate_shearedTensor_eq_self_of_productCovariant
        K hcov a φ ψ
    · simp [L₁, L₂]
    · intro u v _ _ hu hv
      simpa [L₁, L₂] using congrArg₂ (fun x y => x + y) hu hv
    · intro c u _ hu
      simpa [L₁, L₂] using congrArg (fun x => c • x) hu
  exact continuousLinearMap_eq_of_eq_on_dense L₁ L₂ hdense hspan

/-- Conditional product-kernel descent after the sheared product-tensor density
blocker has been supplied.  The unqualified theorem follows from this once
`ShearedProductTensorDense m` is proved by the mixed Schwartz kernel/density
theorem. -/
theorem translationCovariantProductKernel_descends_of_shearedProductTensorDense
    {m : ℕ}
    (hdense : ShearedProductTensorDense m)
    (K : SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ →L[ℂ] ℂ)
    (hcov : ProductKernelRealTranslationCovariantGlobal K)
    (η : SchwartzMap (Fin m → ℝ) ℂ)
    (hη : ∫ t : Fin m → ℝ, η t = 1) :
    ∃ Hdist : SchwartzMap (ComplexChartSpace m) ℂ →L[ℂ] ℂ,
      ∀ (φ : SchwartzMap (ComplexChartSpace m) ℂ)
        (ψ : SchwartzMap (Fin m → ℝ) ℂ),
        K (schwartzTensorProduct₂ φ ψ) = Hdist (realConvolutionTest φ ψ) := by
  let T := shearedProductKernelFunctional K
  let Hdist : SchwartzMap (ComplexChartSpace m) ℂ →L[ℂ] ℂ :=
    complexRealFiberTranslationDescentCLM T η
  have hT : IsComplexRealFiberTranslationInvariant T :=
    shearedProductKernel_fiberInvariant_of_productCovariant_of_shearedProductTensorDense
      hdense K hcov
  refine ⟨Hdist, ?_⟩
  intro φ ψ
  let F := (SchwartzMap.compCLMOfContinuousLinearEquiv ℂ (realConvolutionShearCLE m))
    (schwartzTensorProduct₂ φ ψ)
  have hfac :=
    map_eq_complexRealFiberTranslationDescentCLM_of_fiberTranslationInvariant
      T hT η hη F
  simpa [T, Hdist, F, realConvolutionTest, shearedProductKernelFunctional,
    ContinuousLinearMap.comp_apply] using hfac

/-- Product-kernel descent from the standard unsheared product-density theorem.

The remaining unqualified blocker is now `ProductTensorDense m`, the QFT-free
mixed two-space Schwartz product-density theorem. -/
theorem translationCovariantProductKernel_descends_of_productTensorDense
    {m : ℕ}
    (hdense : ProductTensorDense m)
    (K : SchwartzMap (ComplexChartSpace m × (Fin m → ℝ)) ℂ →L[ℂ] ℂ)
    (hcov : ProductKernelRealTranslationCovariantGlobal K)
    (η : SchwartzMap (Fin m → ℝ) ℂ)
    (hη : ∫ t : Fin m → ℝ, η t = 1) :
    ∃ Hdist : SchwartzMap (ComplexChartSpace m) ℂ →L[ℂ] ℂ,
      ∀ (φ : SchwartzMap (ComplexChartSpace m) ℂ)
        (ψ : SchwartzMap (Fin m → ℝ) ℂ),
        K (schwartzTensorProduct₂ φ ψ) = Hdist (realConvolutionTest φ ψ) :=
  translationCovariantProductKernel_descends_of_shearedProductTensorDense
    (shearedProductTensorDense_of_productTensorDense hdense) K hcov η hη

end SCV
