/-
Copyright (c) 2026 ModularPhysics Contributors.
Released under Apache 2.0 license.
Authors: ModularPhysics Contributors
-/
import OSReconstruction.SCV.LocalEOWChartLinear
import Mathlib.Topology.MetricSpace.Thickening

/-!
# Local EOW Side-Cone Boundary Filters

This file contains the small cone/filter support needed before the local
distributional EOW slice-CLM assembly.  The point is to keep the lower-side
sign change explicit: a lower boundary value written as `x - iη` is a raw
slice limit over the negative image of the positive side cone.
-/

noncomputable section

open Complex Filter Metric Set

namespace SCV

variable {m : ℕ}

/-- Open direction window around the compact simplex of fixed-basis local EOW
directions.  The radius is halved so that this open window sits in the closed
`ε`-thickening used for compact uniform boundary estimates. -/
def localEOWSideDirectionWindow
    (ys : Fin m → Fin m → ℝ) (ε : ℝ) : Set (Fin m → ℝ) :=
  Metric.thickening (ε / 2) (localEOWSimplexDirections ys)

/-- Compact closed direction envelope for the local EOW side cone. -/
def localEOWSideDirectionClosure
    (ys : Fin m → Fin m → ℝ) (ε : ℝ) : Set (Fin m → ℝ) :=
  Metric.cthickening ε (localEOWSimplexDirections ys)

/-- The conic approach domain generated by the open local EOW direction
window. -/
def localEOWSideCone
    (ys : Fin m → Fin m → ℝ) (ε : ℝ) : Set (Fin m → ℝ) :=
  {y | ∃ s : ℝ, 0 < s ∧
    ∃ η ∈ localEOWSideDirectionWindow ys ε, y = s • η}

/-- The open direction window is contained in the compact closed direction
envelope. -/
theorem localEOWSideDirectionWindow_subset_closure
    (ys : Fin m → Fin m → ℝ) {ε : ℝ} (hε : 0 < ε) :
    localEOWSideDirectionWindow ys ε ⊆
      localEOWSideDirectionClosure ys ε := by
  dsimp [localEOWSideDirectionWindow, localEOWSideDirectionClosure]
  exact thickening_subset_cthickening_of_le
    (by linarith : ε / 2 ≤ ε) _

/-- The closed direction envelope is compact. -/
theorem isCompact_localEOWSideDirectionClosure
    (ys : Fin m → Fin m → ℝ) (ε : ℝ) :
    IsCompact (localEOWSideDirectionClosure ys ε) := by
  dsimp [localEOWSideDirectionClosure]
  exact (isCompact_localEOWSimplexDirections ys).cthickening

/-- The fixed simplex directions lie in every positive side-direction
window. -/
theorem localEOWSimplexDirections_subset_sideDirectionWindow
    (ys : Fin m → Fin m → ℝ) {ε : ℝ} (hε : 0 < ε) :
    localEOWSimplexDirections ys ⊆ localEOWSideDirectionWindow ys ε := by
  dsimp [localEOWSideDirectionWindow]
  exact self_subset_thickening (half_pos hε) _

/-- The compact simplex of chart directions does not contain the zero vector
when the chosen chart directions are linearly independent. -/
theorem zero_not_mem_localEOWSimplexDirections
    (ys : Fin m → Fin m → ℝ)
    (hli : LinearIndependent ℝ ys) :
    (0 : Fin m → ℝ) ∉ localEOWSimplexDirections ys := by
  rintro ⟨a, ha, hzero⟩
  have hcoeff : ∀ j, a j = 0 := by
    intro j
    exact Fintype.linearIndependent_iff.mp hli a (by simpa using hzero) j
  have hsum_zero : ∑ j, a j = 0 := by
    simp [hcoeff]
  have hsum_one : ∑ j, a j = 1 := ha.2
  linarith

/-- Choose a positive thickening radius whose closed direction envelope is
still inside the ambient cone and stays away from zero. -/
theorem exists_localEOWSideCone_radius
    (C : Set (Fin m → ℝ))
    (hC_open : IsOpen C)
    (hC_conv : Convex ℝ C)
    (ys : Fin m → Fin m → ℝ)
    (hys_mem : ∀ j, ys j ∈ C)
    (hli : LinearIndependent ℝ ys) :
    ∃ ε : ℝ, 0 < ε ∧
      localEOWSideDirectionClosure ys ε ⊆ C ∩ {η | η ≠ 0} := by
  let K : Set (Fin m → ℝ) := localEOWSimplexDirections ys
  let U : Set (Fin m → ℝ) := C ∩ {η | η ≠ 0}
  have hK_compact : IsCompact K := by
    dsimp [K]
    exact isCompact_localEOWSimplexDirections ys
  have hne_open : IsOpen ({η : Fin m → ℝ | η ≠ 0}) := by
    change IsOpen (({0} : Set (Fin m → ℝ))ᶜ)
    exact isClosed_singleton.isOpen_compl
  have hU_open : IsOpen U := hC_open.inter hne_open
  have hK_U : K ⊆ U := by
    intro η hη
    constructor
    · exact localEOWSimplexDirections_subset_cone C hC_conv ys hys_mem hη
    · intro hη_zero
      exact zero_not_mem_localEOWSimplexDirections ys hli
        (by simpa [hη_zero] using hη)
  obtain ⟨ε, hε, hεsub⟩ :=
    hK_compact.exists_cthickening_subset_open hU_open hK_U
  refine ⟨ε, hε, ?_⟩
  intro η hη
  exact hεsub hη

/-- The conic approach domain generated by an open direction window is open. -/
theorem isOpen_localEOWSideCone
    (ys : Fin m → Fin m → ℝ) (ε : ℝ) :
    IsOpen (localEOWSideCone ys ε) := by
  have hwindow_open : IsOpen (localEOWSideDirectionWindow ys ε) := by
    dsimp [localEOWSideDirectionWindow]
    exact isOpen_thickening
  rw [show localEOWSideCone ys ε =
      ⋃ s : {s : ℝ // 0 < s},
        ((fun η : Fin m → ℝ => (s : ℝ) • η) ''
          localEOWSideDirectionWindow ys ε) by
    ext y
    constructor
    · rintro ⟨s, hs, η, hη, rfl⟩
      exact Set.mem_iUnion.mpr ⟨⟨s, hs⟩, ⟨η, hη, rfl⟩⟩
    · intro hy
      rcases Set.mem_iUnion.mp hy with ⟨s, hy⟩
      rcases hy with ⟨η, hη, rfl⟩
      exact ⟨s, s.property, η, hη, rfl⟩]
  apply isOpen_iUnion
  intro s
  have hs_ne : (s : ℝ) ≠ 0 := ne_of_gt s.property
  simpa [Homeomorph.smulOfNeZero_apply] using
    ((Homeomorph.smulOfNeZero (s : ℝ) hs_ne).isOpen_image).2
      hwindow_open

/-- Negation carries open sets to open sets. -/
theorem isOpen_neg_image
    (C : Set (Fin m → ℝ)) (hC : IsOpen C) :
    IsOpen (Neg.neg '' C) := by
  simpa [Homeomorph.coe_neg] using
    ((Homeomorph.neg (Fin m → ℝ)).isOpen_image).2 hC

/-- Positive coordinate imaginary parts map into the local side cone after
normalizing by their coordinate sum. -/
theorem localEOWRealLinearPart_mem_localEOWSideCone
    (ys : Fin m → Fin m → ℝ) {ε : ℝ} (hε : 0 < ε)
    {v : Fin m → ℝ}
    (hv_nonneg : ∀ j, 0 ≤ v j)
    (hv_sum_pos : 0 < ∑ j, v j) :
    localEOWRealLinearPart ys v ∈ localEOWSideCone ys ε := by
  let s : ℝ := ∑ j, v j
  let η : Fin m → ℝ := s⁻¹ • localEOWRealLinearPart ys v
  refine ⟨s, by simpa [s] using hv_sum_pos, η, ?_, ?_⟩
  · apply localEOWSimplexDirections_subset_sideDirectionWindow ys hε
    dsimp [η, s]
    rw [localEOWRealLinearPart_eq_sum_smul]
    exact localEOW_positive_imag_normalized_mem_simplex
      (ys := ys) hv_nonneg hv_sum_pos
  · ext a
    have hs_ne : s ≠ 0 := ne_of_gt (by simpa [s] using hv_sum_pos)
    simp [η, hs_ne]

/-- The generated local side cone stays inside the ambient cone when the
closed direction envelope does. -/
theorem localEOWSideCone_subset_cone
    (C : Set (Fin m → ℝ))
    (hC_cone : ∀ t : ℝ, 0 < t → ∀ y ∈ C, t • y ∈ C)
    (ys : Fin m → Fin m → ℝ) {ε : ℝ} (hε : 0 < ε)
    (hclosure_C : localEOWSideDirectionClosure ys ε ⊆ C) :
    localEOWSideCone ys ε ⊆ C := by
  rintro y ⟨s, hs, η, hη, rfl⟩
  exact hC_cone s hs η
    (hclosure_C (localEOWSideDirectionWindow_subset_closure ys hε hη))

/-- A compact closed direction envelope avoiding zero has a uniform positive
norm lower bound. -/
theorem localEOWSideCone_direction_norm_bound
    (ys : Fin m → Fin m → ℝ) (ε : ℝ)
    (hclosure_nonzero :
      localEOWSideDirectionClosure ys ε ⊆ {η | η ≠ 0}) :
    ∃ c : ℝ, 0 < c ∧
      ∀ η ∈ localEOWSideDirectionClosure ys ε, c ≤ ‖η‖ := by
  obtain ⟨c, hc_pos, hc_le⟩ :=
    (isCompact_localEOWSideDirectionClosure ys ε).exists_forall_le'
      (f := fun η : Fin m → ℝ => ‖η‖)
      continuous_norm.continuousOn
      (a := 0)
      (by
        intro η hη
        exact norm_pos_iff.mpr (hclosure_nonzero hη))
  exact ⟨c, hc_pos, hc_le⟩

/-- In a side-cone representation `y = s • η`, a uniform lower bound on
`‖η‖` controls the scalar by `‖y‖`. -/
theorem localEOWSideCone_scalar_le_norm_div
    {c s : ℝ} {η y : Fin m → ℝ}
    (hc : 0 < c) (hs : 0 < s) (hη : c ≤ ‖η‖) (hy : y = s • η) :
    s ≤ ‖y‖ / c := by
  have hs_nonneg : 0 ≤ s := le_of_lt hs
  have hmul : s * c ≤ ‖y‖ := by
    calc
      s * c ≤ s * ‖η‖ := mul_le_mul_of_nonneg_left hη hs_nonneg
      _ = ‖s • η‖ := by
        rw [norm_smul, Real.norm_eq_abs, abs_of_pos hs]
      _ = ‖y‖ := by rw [hy]
  exact (le_div_iff₀ hc).2 hmul

/-- Negation sends the edge filter on the negative image of a cone to the edge
filter on the original cone. -/
theorem tendsto_neg_nhdsWithin_zero_neg_image
    (C : Set (Fin m → ℝ)) :
    Filter.Tendsto (fun y : Fin m → ℝ => -y)
      (nhdsWithin 0 (Neg.neg '' C)) (nhdsWithin 0 C) := by
  have hcont0 : ContinuousAt (fun y : Fin m → ℝ => -y) (0 : Fin m → ℝ) :=
    continuous_neg.continuousAt
  have hmaps : Set.MapsTo (fun y : Fin m → ℝ => -y) (Neg.neg '' C) C := by
    rintro y ⟨x, hx, rfl⟩
    simpa using hx
  simpa using hcont0.continuousWithinAt.tendsto_nhdsWithin hmaps

/-- Convert OS-II uniform-on-compact direction boundary values into raw
`nhdsWithin` boundary values on a relatively compact local EOW side cone and
its negative image. -/
theorem localEOW_basisSideCone_rawBoundaryValue
    (E C : Set (Fin m → ℝ))
    (hC_open : IsOpen C)
    (hC_conv : Convex ℝ C)
    (hC_cone : ∀ t : ℝ, 0 < t → ∀ y ∈ C, t • y ∈ C)
    (ys : Fin m → Fin m → ℝ)
    (hys_mem : ∀ j, ys j ∈ C)
    (hli : LinearIndependent ℝ ys)
    (Fplus Fminus : ComplexChartSpace m → ℂ)
    (Traw : SchwartzMap (Fin m → ℝ) ℂ →L[ℝ] ℂ)
    (hplus_bv_uniform :
      ∀ Kη : Set (Fin m → ℝ), IsCompact Kη → Kη ⊆ C →
        ∀ φ : SchwartzMap (Fin m → ℝ) ℂ,
          HasCompactSupport (φ : (Fin m → ℝ) → ℂ) →
          tsupport (φ : (Fin m → ℝ) → ℂ) ⊆ E →
          TendstoUniformlyOn
            (fun (ε : ℝ) η =>
              ∫ x : Fin m → ℝ,
                Fplus (fun a => (x a : ℂ) +
                  (ε : ℂ) * (η a : ℂ) * Complex.I) * φ x)
            (fun _ : Fin m → ℝ => Traw φ)
            (nhdsWithin 0 (Set.Ioi 0))
            Kη)
    (hminus_bv_uniform :
      ∀ Kη : Set (Fin m → ℝ), IsCompact Kη → Kη ⊆ C →
        ∀ φ : SchwartzMap (Fin m → ℝ) ℂ,
          HasCompactSupport (φ : (Fin m → ℝ) → ℂ) →
          tsupport (φ : (Fin m → ℝ) → ℂ) ⊆ E →
          TendstoUniformlyOn
            (fun (ε : ℝ) η =>
              ∫ x : Fin m → ℝ,
                Fminus (fun a => (x a : ℂ) -
                  (ε : ℂ) * (η a : ℂ) * Complex.I) * φ x)
            (fun _ : Fin m → ℝ => Traw φ)
            (nhdsWithin 0 (Set.Ioi 0))
            Kη) :
    ∃ ε : ℝ, ∃ Cplus Cminus : Set (Fin m → ℝ),
      0 < ε ∧
      Cplus = localEOWSideCone ys ε ∧
      Cminus = Neg.neg '' Cplus ∧
      localEOWSideDirectionClosure ys ε ⊆ C ∩ {η | η ≠ 0} ∧
      IsOpen Cplus ∧ IsOpen Cminus ∧
      localEOWSimplexDirections ys ⊆ Cplus ∧
      Cplus ⊆ C ∧
      (∀ v, (∀ j, 0 ≤ v j) → 0 < ∑ j, v j →
        localEOWRealLinearPart ys v ∈ Cplus) ∧
      (∀ φ : SchwartzMap (Fin m → ℝ) ℂ,
        HasCompactSupport (φ : (Fin m → ℝ) → ℂ) →
        tsupport (φ : (Fin m → ℝ) → ℂ) ⊆ E →
        Filter.Tendsto (fun y =>
          ∫ x, Fplus (fun i => (x i : ℂ) + ((y i : ℝ) : ℂ) *
            Complex.I) * φ x)
          (nhdsWithin 0 Cplus) (nhds (Traw φ))) ∧
      (∀ φ : SchwartzMap (Fin m → ℝ) ℂ,
        HasCompactSupport (φ : (Fin m → ℝ) → ℂ) →
        tsupport (φ : (Fin m → ℝ) → ℂ) ⊆ E →
        Filter.Tendsto (fun y =>
          ∫ x, Fminus (fun i => (x i : ℂ) + ((y i : ℝ) : ℂ) *
            Complex.I) * φ x)
          (nhdsWithin 0 Cminus) (nhds (Traw φ))) := by
  classical
  obtain ⟨ε, hε, hεsub⟩ :=
    exists_localEOWSideCone_radius C hC_open hC_conv ys hys_mem hli
  let Cplus : Set (Fin m → ℝ) := localEOWSideCone ys ε
  let Cminus : Set (Fin m → ℝ) := Neg.neg '' Cplus
  have hclosure_C : localEOWSideDirectionClosure ys ε ⊆ C := fun η hη =>
    (hεsub hη).1
  have hclosure_nonzero :
      localEOWSideDirectionClosure ys ε ⊆ {η | η ≠ 0} :=
    fun η hη => (hεsub hη).2
  obtain ⟨c, hc_pos, hc_le⟩ :=
    localEOWSideCone_direction_norm_bound ys ε hclosure_nonzero
  have hCplus_open : IsOpen Cplus := by
    dsimp [Cplus]
    exact isOpen_localEOWSideCone ys ε
  have hCminus_open : IsOpen Cminus := by
    dsimp [Cminus]
    exact isOpen_neg_image Cplus hCplus_open
  have hsimplex_Cplus : localEOWSimplexDirections ys ⊆ Cplus := by
    intro η hη
    refine ⟨1, by norm_num, η,
      localEOWSimplexDirections_subset_sideDirectionWindow ys hε hη, ?_⟩
    simp
  have hCplus_C : Cplus ⊆ C := by
    dsimp [Cplus]
    exact localEOWSideCone_subset_cone C hC_cone ys hε hclosure_C
  have himag_mem : ∀ v, (∀ j, 0 ≤ v j) → 0 < ∑ j, v j →
      localEOWRealLinearPart ys v ∈ Cplus := by
    intro v hv_nonneg hv_sum_pos
    dsimp [Cplus]
    exact localEOWRealLinearPart_mem_localEOWSideCone ys hε
      hv_nonneg hv_sum_pos
  refine ⟨ε, Cplus, Cminus, hε, rfl, rfl, hεsub, hCplus_open,
    hCminus_open, hsimplex_Cplus, hCplus_C, himag_mem, ?_, ?_⟩
  · intro φ hφ_compact hφ_support
    let Kcl : Set (Fin m → ℝ) := localEOWSideDirectionClosure ys ε
    let sideScalar : (Fin m → ℝ) → ℝ := fun y =>
      if hy : y ∈ Cplus then Classical.choose hy else 0
    let sideDirection : (Fin m → ℝ) → Fin m → ℝ := fun y =>
      if hy : y ∈ Cplus then
        Classical.choose (Classical.choose_spec hy).2
      else 0
    have hrep_event : ∀ᶠ y in nhdsWithin 0 Cplus,
        0 < sideScalar y ∧ sideDirection y ∈ Kcl ∧
        y = sideScalar y • sideDirection y := by
      filter_upwards [self_mem_nhdsWithin] with y hy
      have hs := Classical.choose_spec hy
      have hη := Classical.choose_spec hs.2
      have hscalar : sideScalar y = Classical.choose hy := by
        simp [sideScalar, hy]
      have hdir : sideDirection y = Classical.choose hs.2 := by
        simp [sideDirection, hy]
      constructor
      · simpa [hscalar] using hs.1
      constructor
      · dsimp [Kcl]
        exact localEOWSideDirectionWindow_subset_closure ys hε
          (by simpa [hdir] using hη.1)
      · simpa [hscalar, hdir] using hη.2
    have hscalar_nhds :
        Filter.Tendsto sideScalar (nhdsWithin 0 Cplus) (nhds 0) := by
      rw [Metric.tendsto_nhds]
      intro δ hδ
      have hdc_pos : 0 < δ * c := mul_pos hδ hc_pos
      have hy_small : ∀ᶠ y in nhdsWithin 0 Cplus, ‖y‖ < δ * c := by
        have hball :
            Metric.ball (0 : Fin m → ℝ) (δ * c) ∈
              nhds (0 : Fin m → ℝ) :=
          Metric.ball_mem_nhds _ hdc_pos
        have hball_within :
            Metric.ball (0 : Fin m → ℝ) (δ * c) ∈
              nhdsWithin (0 : Fin m → ℝ) Cplus :=
          (show nhdsWithin (0 : Fin m → ℝ) Cplus ≤
              nhds (0 : Fin m → ℝ) from inf_le_left) hball
        filter_upwards [hball_within] with y hy
        simpa [Metric.mem_ball, dist_zero_right] using hy
      filter_upwards [hrep_event, hy_small] with y hrep hy_norm
      have hs_le : sideScalar y ≤ ‖y‖ / c :=
        localEOWSideCone_scalar_le_norm_div hc_pos hrep.1
          (hc_le (sideDirection y) (by simpa [Kcl] using hrep.2.1))
          hrep.2.2
      have hs_nonneg : 0 ≤ sideScalar y := le_of_lt hrep.1
      have hs_lt : sideScalar y < δ := by
        have hdiv_lt : ‖y‖ / c < δ :=
          (div_lt_iff₀ hc_pos).2 (by simpa [mul_comm] using hy_norm)
        exact lt_of_le_of_lt hs_le hdiv_lt
      rw [dist_eq_norm]
      change ‖sideScalar y - 0‖ < δ
      rw [sub_zero, Real.norm_eq_abs, abs_of_nonneg hs_nonneg]
      exact hs_lt
    have hscalar_tendsto : Filter.Tendsto sideScalar (nhdsWithin 0 Cplus)
        (nhdsWithin 0 (Set.Ioi 0)) := by
      rw [tendsto_nhdsWithin_iff]
      constructor
      · exact hscalar_nhds
      · filter_upwards [hrep_event] with y hrep
        exact hrep.1
    have hdir_event : ∀ᶠ y in nhdsWithin 0 Cplus, sideDirection y ∈ Kcl := by
      filter_upwards [hrep_event] with y hrep
      exact hrep.2.1
    have hKcl_compact : IsCompact Kcl := by
      dsimp [Kcl]
      exact isCompact_localEOWSideDirectionClosure ys ε
    have hKcl_C : Kcl ⊆ C := by
      intro η hη
      exact hclosure_C (by simpa [Kcl] using hη)
    have hplus_uniform :=
      hplus_bv_uniform Kcl hKcl_compact hKcl_C φ hφ_compact hφ_support
    have hplus_comp :
        Filter.Tendsto
          (fun y : Fin m → ℝ =>
            ∫ x : Fin m → ℝ,
              Fplus (fun i => (x i : ℂ) +
                (sideScalar y : ℂ) *
                  (sideDirection y i : ℂ) * Complex.I) * φ x)
          (nhdsWithin 0 Cplus) (nhds (Traw φ)) := by
      exact tendstoUniformlyOn_const_comp_of_tendsto_of_eventually_mem
        (F := fun (ε : ℝ) (η : Fin m → ℝ) =>
          ∫ x : Fin m → ℝ,
            Fplus (fun i => (x i : ℂ) +
              (ε : ℂ) * (η i : ℂ) * Complex.I) * φ x)
        (c := Traw φ) (a := sideScalar) (b := sideDirection)
        hplus_uniform hscalar_tendsto hdir_event
    have hplus_eq :
        (fun y : Fin m → ℝ =>
            ∫ x : Fin m → ℝ,
              Fplus (fun i => (x i : ℂ) +
                (sideScalar y : ℂ) *
                  (sideDirection y i : ℂ) * Complex.I) * φ x) =ᶠ[
          nhdsWithin 0 Cplus]
          (fun y : Fin m → ℝ =>
            ∫ x : Fin m → ℝ,
              Fplus (fun i => (x i : ℂ) + ((y i : ℝ) : ℂ) *
                Complex.I) * φ x) := by
      filter_upwards [hrep_event] with y hrep
      apply MeasureTheory.integral_congr_ae
      filter_upwards with x
      symm
      congr 2
      ext i
      have hyi : y i = sideScalar y * sideDirection y i := by
        simpa [Pi.smul_apply] using congrFun hrep.2.2 i
      rw [hyi]
      norm_num
    exact hplus_comp.congr' hplus_eq
  · intro φ hφ_compact hφ_support
    let Kcl : Set (Fin m → ℝ) := localEOWSideDirectionClosure ys ε
    let sideScalar : (Fin m → ℝ) → ℝ := fun y =>
      if hy : y ∈ Cplus then Classical.choose hy else 0
    let sideDirection : (Fin m → ℝ) → Fin m → ℝ := fun y =>
      if hy : y ∈ Cplus then
        Classical.choose (Classical.choose_spec hy).2
      else 0
    have hrep_event : ∀ᶠ y in nhdsWithin 0 Cplus,
        0 < sideScalar y ∧ sideDirection y ∈ Kcl ∧
        y = sideScalar y • sideDirection y := by
      filter_upwards [self_mem_nhdsWithin] with y hy
      have hs := Classical.choose_spec hy
      have hη := Classical.choose_spec hs.2
      have hscalar : sideScalar y = Classical.choose hy := by
        simp [sideScalar, hy]
      have hdir : sideDirection y = Classical.choose hs.2 := by
        simp [sideDirection, hy]
      constructor
      · simpa [hscalar] using hs.1
      constructor
      · dsimp [Kcl]
        exact localEOWSideDirectionWindow_subset_closure ys hε
          (by simpa [hdir] using hη.1)
      · simpa [hscalar, hdir] using hη.2
    have hscalar_nhds :
        Filter.Tendsto sideScalar (nhdsWithin 0 Cplus) (nhds 0) := by
      rw [Metric.tendsto_nhds]
      intro δ hδ
      have hdc_pos : 0 < δ * c := mul_pos hδ hc_pos
      have hy_small : ∀ᶠ y in nhdsWithin 0 Cplus, ‖y‖ < δ * c := by
        have hball :
            Metric.ball (0 : Fin m → ℝ) (δ * c) ∈
              nhds (0 : Fin m → ℝ) :=
          Metric.ball_mem_nhds _ hdc_pos
        have hball_within :
            Metric.ball (0 : Fin m → ℝ) (δ * c) ∈
              nhdsWithin (0 : Fin m → ℝ) Cplus :=
          (show nhdsWithin (0 : Fin m → ℝ) Cplus ≤
              nhds (0 : Fin m → ℝ) from inf_le_left) hball
        filter_upwards [hball_within] with y hy
        simpa [Metric.mem_ball, dist_zero_right] using hy
      filter_upwards [hrep_event, hy_small] with y hrep hy_norm
      have hs_le : sideScalar y ≤ ‖y‖ / c :=
        localEOWSideCone_scalar_le_norm_div hc_pos hrep.1
          (hc_le (sideDirection y) (by simpa [Kcl] using hrep.2.1))
          hrep.2.2
      have hs_nonneg : 0 ≤ sideScalar y := le_of_lt hrep.1
      have hs_lt : sideScalar y < δ := by
        have hdiv_lt : ‖y‖ / c < δ :=
          (div_lt_iff₀ hc_pos).2 (by simpa [mul_comm] using hy_norm)
        exact lt_of_le_of_lt hs_le hdiv_lt
      rw [dist_eq_norm]
      change ‖sideScalar y - 0‖ < δ
      rw [sub_zero, Real.norm_eq_abs, abs_of_nonneg hs_nonneg]
      exact hs_lt
    have hscalar_tendsto : Filter.Tendsto sideScalar (nhdsWithin 0 Cplus)
        (nhdsWithin 0 (Set.Ioi 0)) := by
      rw [tendsto_nhdsWithin_iff]
      constructor
      · exact hscalar_nhds
      · filter_upwards [hrep_event] with y hrep
        exact hrep.1
    have hdir_event : ∀ᶠ y in nhdsWithin 0 Cplus, sideDirection y ∈ Kcl := by
      filter_upwards [hrep_event] with y hrep
      exact hrep.2.1
    have hKcl_compact : IsCompact Kcl := by
      dsimp [Kcl]
      exact isCompact_localEOWSideDirectionClosure ys ε
    have hKcl_C : Kcl ⊆ C := by
      intro η hη
      exact hclosure_C (by simpa [Kcl] using hη)
    have hminus_uniform :=
      hminus_bv_uniform Kcl hKcl_compact hKcl_C φ hφ_compact hφ_support
    have hminus_comp_plus :
        Filter.Tendsto
          (fun y : Fin m → ℝ =>
            ∫ x : Fin m → ℝ,
              Fminus (fun i => (x i : ℂ) -
                (sideScalar y : ℂ) *
                  (sideDirection y i : ℂ) * Complex.I) * φ x)
          (nhdsWithin 0 Cplus) (nhds (Traw φ)) := by
      exact tendstoUniformlyOn_const_comp_of_tendsto_of_eventually_mem
        (F := fun (ε : ℝ) (η : Fin m → ℝ) =>
          ∫ x : Fin m → ℝ,
            Fminus (fun i => (x i : ℂ) -
              (ε : ℂ) * (η i : ℂ) * Complex.I) * φ x)
        (c := Traw φ) (a := sideScalar) (b := sideDirection)
        hminus_uniform hscalar_tendsto hdir_event
    have hminus_eq_plus :
        (fun y : Fin m → ℝ =>
            ∫ x : Fin m → ℝ,
              Fminus (fun i => (x i : ℂ) -
                (sideScalar y : ℂ) *
                  (sideDirection y i : ℂ) * Complex.I) * φ x) =ᶠ[
          nhdsWithin 0 Cplus]
          (fun y : Fin m → ℝ =>
            ∫ x : Fin m → ℝ,
              Fminus (fun i => (x i : ℂ) - ((y i : ℝ) : ℂ) *
                Complex.I) * φ x) := by
      filter_upwards [hrep_event] with y hrep
      apply MeasureTheory.integral_congr_ae
      filter_upwards with x
      symm
      congr 2
      ext i
      have hyi : y i = sideScalar y * sideDirection y i := by
        simpa [Pi.smul_apply] using congrFun hrep.2.2 i
      rw [hyi]
      norm_num
    have hminus_on_plus :
        Filter.Tendsto
          (fun y : Fin m → ℝ =>
            ∫ x : Fin m → ℝ,
              Fminus (fun i => (x i : ℂ) - ((y i : ℝ) : ℂ) *
                Complex.I) * φ x)
          (nhdsWithin 0 Cplus) (nhds (Traw φ)) :=
      hminus_comp_plus.congr' hminus_eq_plus
    have hminus_comp_minus :=
      hminus_on_plus.comp (tendsto_neg_nhdsWithin_zero_neg_image Cplus)
    have hminus_eq_minus :
        (fun y : Fin m → ℝ =>
            ∫ x : Fin m → ℝ,
              Fminus (fun i => (x i : ℂ) -
                (((-y) i : ℝ) : ℂ) * Complex.I) * φ x) =ᶠ[
          nhdsWithin 0 Cminus]
          (fun y : Fin m → ℝ =>
            ∫ x : Fin m → ℝ,
              Fminus (fun i => (x i : ℂ) + ((y i : ℝ) : ℂ) *
                Complex.I) * φ x) := by
      filter_upwards with y
      apply MeasureTheory.integral_congr_ae
      filter_upwards with x
      congr 2
      ext i
      simp
    exact hminus_comp_minus.congr' hminus_eq_minus

/-- Truncate the explicit local EOW side cones by a small ball so that a fixed
compactly supported cutoff has honest one-sided holomorphy margins. -/
theorem exists_localEOW_truncatedSideCones_for_sliceMargin
    (E C : Set (Fin m → ℝ))
    (Ωplus Ωminus : Set (ComplexChartSpace m))
    (hlocal_wedge :
      ∀ K : Set (Fin m → ℝ), IsCompact K → K ⊆ E →
        ∀ Kη : Set (Fin m → ℝ), IsCompact Kη → Kη ⊆ C →
          ∃ r : ℝ, 0 < r ∧
            ∀ x ∈ K, ∀ η ∈ Kη, ∀ ε : ℝ, 0 < ε → ε < r →
              (fun a => (x a : ℂ) +
                (ε : ℂ) * (η a : ℂ) * Complex.I) ∈ Ωplus ∧
              (fun a => (x a : ℂ) -
                (ε : ℂ) * (η a : ℂ) * Complex.I) ∈ Ωminus)
    (ys : Fin m → Fin m → ℝ)
    {ε : ℝ}
    (hε : 0 < ε)
    (hclosure :
      localEOWSideDirectionClosure ys ε ⊆ C ∩ {η | η ≠ 0})
    (χ : SchwartzMap (Fin m → ℝ) ℂ)
    (hχ_compact : HasCompactSupport (χ : (Fin m → ℝ) → ℂ))
    (hχ_E : tsupport (χ : (Fin m → ℝ) → ℂ) ⊆ E) :
    ∃ rside : ℝ, ∃ CplusLoc CminusLoc : Set (Fin m → ℝ),
      0 < rside ∧
      CplusLoc = localEOWSideCone ys ε ∩ Metric.ball 0 rside ∧
      CminusLoc = Neg.neg '' CplusLoc ∧
      IsOpen CplusLoc ∧ IsOpen CminusLoc ∧
      CplusLoc ⊆ localEOWSideCone ys ε ∧
      CminusLoc ⊆ Neg.neg '' localEOWSideCone ys ε ∧
      (∀ y ∈ CplusLoc, ∀ x ∈ tsupport (χ : (Fin m → ℝ) → ℂ),
        (fun i => (x i : ℂ) + ((y i : ℝ) : ℂ) * Complex.I) ∈ Ωplus) ∧
      (∀ y ∈ CminusLoc, ∀ x ∈ tsupport (χ : (Fin m → ℝ) → ℂ),
        (fun i => (x i : ℂ) + ((y i : ℝ) : ℂ) * Complex.I) ∈ Ωminus) := by
  classical
  let K : Set (Fin m → ℝ) := tsupport (χ : (Fin m → ℝ) → ℂ)
  let Kη : Set (Fin m → ℝ) := localEOWSideDirectionClosure ys ε
  have hK_compact : IsCompact K := by
    simpa [K, HasCompactSupport] using hχ_compact
  have hK_E : K ⊆ E := by
    simpa [K] using hχ_E
  have hKη_compact : IsCompact Kη := by
    simpa [Kη] using isCompact_localEOWSideDirectionClosure ys ε
  have hKη_C : Kη ⊆ C := by
    intro η hη
    exact (hclosure (by simpa [Kη] using hη)).1
  obtain ⟨rwedge, hrwedge_pos, hwedge⟩ :=
    hlocal_wedge K hK_compact hK_E Kη hKη_compact hKη_C
  have hclosure_nonzero :
      localEOWSideDirectionClosure ys ε ⊆ {η | η ≠ 0} := by
    intro η hη
    exact (hclosure hη).2
  obtain ⟨c, hc_pos, hc_le⟩ :=
    localEOWSideCone_direction_norm_bound ys ε hclosure_nonzero
  let rside : ℝ := rwedge * c / 2
  let CplusLoc : Set (Fin m → ℝ) :=
    localEOWSideCone ys ε ∩ Metric.ball (0 : Fin m → ℝ) rside
  let CminusLoc : Set (Fin m → ℝ) := Neg.neg '' CplusLoc
  have hrside_pos : 0 < rside := by
    dsimp [rside]
    nlinarith [hrwedge_pos, hc_pos]
  have hCplusLoc_open : IsOpen CplusLoc := by
    dsimp [CplusLoc]
    exact (isOpen_localEOWSideCone ys ε).inter isOpen_ball
  have hCminusLoc_open : IsOpen CminusLoc := by
    dsimp [CminusLoc]
    exact isOpen_neg_image CplusLoc hCplusLoc_open
  have hCplusLoc_sub : CplusLoc ⊆ localEOWSideCone ys ε := by
    intro y hy
    exact hy.1
  have hCminusLoc_sub : CminusLoc ⊆ Neg.neg '' localEOWSideCone ys ε := by
    rintro y ⟨yp, hyp, rfl⟩
    exact ⟨yp, hyp.1, rfl⟩
  have hplus_margin :
      ∀ y ∈ CplusLoc, ∀ x ∈ tsupport (χ : (Fin m → ℝ) → ℂ),
        (fun i => (x i : ℂ) + ((y i : ℝ) : ℂ) * Complex.I) ∈ Ωplus := by
    intro y hy x hx
    rcases hy.1 with ⟨s, hs, η, hη_window, hy_eq⟩
    have hη_closure :
        η ∈ localEOWSideDirectionClosure ys ε :=
      localEOWSideDirectionWindow_subset_closure ys hε hη_window
    have hs_lt : s < rwedge := by
      have hy_norm : ‖y‖ < rside := by
        simpa [CplusLoc, Metric.mem_ball, dist_eq_norm] using hy.2
      have hy_norm_big : ‖y‖ < rwedge * c := by
        dsimp [rside] at hy_norm
        nlinarith [hy_norm, hrwedge_pos, hc_pos]
      have hs_le : s ≤ ‖y‖ / c :=
        localEOWSideCone_scalar_le_norm_div hc_pos hs
          (hc_le η hη_closure) hy_eq
      have hdiv_lt : ‖y‖ / c < rwedge :=
        (div_lt_iff₀ hc_pos).2 (by simpa [mul_comm] using hy_norm_big)
      exact lt_of_le_of_lt hs_le hdiv_lt
    have hside := (hwedge x (by simpa [K] using hx) η
      (by simpa [Kη] using hη_closure) s hs hs_lt).1
    have hpoint :
        (fun i => (x i : ℂ) + ((y i : ℝ) : ℂ) * Complex.I) =
          (fun i => (x i : ℂ) +
            (s : ℂ) * (η i : ℂ) * Complex.I) := by
      ext i
      have hyi : y i = s * η i := by
        simpa [Pi.smul_apply] using congrFun hy_eq i
      simp [hyi, mul_assoc]
    simpa [hpoint] using hside
  have hminus_margin :
      ∀ y ∈ CminusLoc, ∀ x ∈ tsupport (χ : (Fin m → ℝ) → ℂ),
        (fun i => (x i : ℂ) + ((y i : ℝ) : ℂ) * Complex.I) ∈ Ωminus := by
    rintro y ⟨yp, hyp, rfl⟩ x hx
    rcases hyp.1 with ⟨s, hs, η, hη_window, hyp_eq⟩
    have hη_closure :
        η ∈ localEOWSideDirectionClosure ys ε :=
      localEOWSideDirectionWindow_subset_closure ys hε hη_window
    have hs_lt : s < rwedge := by
      have hyp_norm : ‖yp‖ < rside := by
        simpa [CplusLoc, Metric.mem_ball, dist_eq_norm] using hyp.2
      have hyp_norm_big : ‖yp‖ < rwedge * c := by
        dsimp [rside] at hyp_norm
        nlinarith [hyp_norm, hrwedge_pos, hc_pos]
      have hs_le : s ≤ ‖yp‖ / c :=
        localEOWSideCone_scalar_le_norm_div hc_pos hs
          (hc_le η hη_closure) hyp_eq
      have hdiv_lt : ‖yp‖ / c < rwedge :=
        (div_lt_iff₀ hc_pos).2 (by simpa [mul_comm] using hyp_norm_big)
      exact lt_of_le_of_lt hs_le hdiv_lt
    have hside := (hwedge x (by simpa [K] using hx) η
      (by simpa [Kη] using hη_closure) s hs hs_lt).2
    have hpoint :
        (fun i => (x i : ℂ) + (((-yp) i : ℝ) : ℂ) * Complex.I) =
          (fun i => (x i : ℂ) -
            (s : ℂ) * (η i : ℂ) * Complex.I) := by
      ext i
      have hypi : yp i = s * η i := by
        simpa [Pi.smul_apply] using congrFun hyp_eq i
      simp [hypi, sub_eq_add_neg, mul_assoc]
    rw [hpoint]
    exact hside
  exact ⟨rside, CplusLoc, CminusLoc, hrside_pos, rfl, rfl,
    hCplusLoc_open, hCminusLoc_open, hCplusLoc_sub, hCminusLoc_sub,
    hplus_margin, hminus_margin⟩

/-- A sufficiently small chart-coordinate ball maps inside any prescribed
ball under the local EOW real-linear part. -/
theorem exists_localEOWRealLinearPart_ball_subset
    (ys : Fin m → Fin m → ℝ)
    {rside : ℝ} (hrside : 0 < rside) :
    ∃ δside : ℝ, 0 < δside ∧
      ∀ v : Fin m → ℝ, ‖v‖ < δside →
        ‖localEOWRealLinearPart ys v‖ < rside := by
  let L₀ : (Fin m → ℝ) →ₗ[ℝ] (Fin m → ℝ) :=
    { toFun := localEOWRealLinearPart ys
      map_add' := localEOWRealLinearPart_add ys
      map_smul' := localEOWRealLinearPart_smul ys }
  let L : (Fin m → ℝ) →L[ℝ] (Fin m → ℝ) :=
    ⟨L₀, L₀.continuous_of_finiteDimensional⟩
  have hpre :
      (fun v : Fin m → ℝ => localEOWRealLinearPart ys v) ⁻¹'
          Metric.ball 0 rside ∈ nhds (0 : Fin m → ℝ) := by
    have hball : Metric.ball (L 0) rside ∈ nhds (L 0) :=
      Metric.ball_mem_nhds _ hrside
    simpa [L, L₀, localEOWRealLinearPart_zero] using
      L.continuous.continuousAt.preimage_mem_nhds hball
  rcases Metric.mem_nhds_iff.mp hpre with ⟨δside, hδside_pos, hδside_sub⟩
  refine ⟨δside, hδside_pos, ?_⟩
  intro v hv
  have hv_ball : v ∈ Metric.ball (0 : Fin m → ℝ) δside := by
    simpa [Metric.mem_ball, dist_eq_norm] using hv
  have hv_image := hδside_sub hv_ball
  simpa [Metric.mem_ball, dist_eq_norm, localEOWRealLinearPart_zero] using
    hv_image

end SCV
